import type { Metadata } from "next";
import { Poppins } from 'next/font/google';
import "./globals.css";
import QueryProvider from "@/provider/queryProvider";
import { Toaster } from "sonner";
import TopLoader from "nextjs-toploader";
const geistSans = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-geist-sans",
});

export const metadata: Metadata = {
  title: "",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className}  antialiased`}
      >
        <QueryProvider>
          <TopLoader color="#147575" shadow="0 0 10px #147575, 0 0 5px #147575" showSpinner={false} height={4} easing="ease-in" />
          {children}
          <Toaster />
        </QueryProvider>
      </body>
    </html>
  );
}
